// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanHang.Models;

namespace WebBanHang.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240528021423_SeedDataToTable")]
    partial class SeedDataToTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebBanHang.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Rolex"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Omega"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Hublot"
                        });
                });

            modelBuilder.Entity("WebBanHang.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Đồng hồ Rolex Datejust M126233-0017",
                            Price = 300.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Đồng Hồ Rolex Datejust 31 278381RBR",
                            Price = 350.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Đồng Hồ Rolex Datejust 31",
                            Price = 400.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Rolex M126234-0051",
                            Price = 420.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "AQUA TERRA 150MCO‑AXIAL MASTER CHRONOMETER 41 MM",
                            Price = 630.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Omega Seamaster 220.10.41.21.03.001 Aqua Terra 41mm",
                            Price = 750.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Đồng hồ Nam Omega Seamaster 210.90.42.20.01.001 Diver 300M 007 Edition",
                            Price = 820.0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Đồng hồ Omega Seamaster Aqua Terra Co-Axial Day Date",
                            Price = 950.0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Hublot 582.NX.1170.RX.1704",
                            Price = 1200.0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Name = "Hublot 542.OX.1181.LR",
                            Price = 1450.0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Name = "Đồng hồ Hublot Spirit of Big Bang King Gold Rainbow 641.OX.0110.LR.0999",
                            Price = 750.0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Name = "Đồng hồ Hublot Classic Fusion Takashi Murakami Sapphire Rainbow 507.JX.0800.RT.TAK21 507JX0800RTTAK21",
                            Price = 1250.0
                        });
                });

            modelBuilder.Entity("WebBanHang.Models.Product", b =>
                {
                    b.HasOne("WebBanHang.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
